### ISSUE TITLE
ServiceManager initializationError 

### ISSUE THREAD

**Issue by scottcsims** [partnet/seauto#15]
I am seeing this error when I try to run my integration test. 

WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]

**Comment by scottcsims** [comment]
I have been digging through this for a while trying to figure out what is referencing the ServiceManager. What other information could I provide that will help with this?

**Comment by bbarke** [comment]
I apologize about the late response. I'm not familiar with that error code. Does your project have it's own version of Guava, or a dependency that relies on it?

**Comment by bbarke** [comment]
The reason i'm asking is because `com.google.common.util.concurrent` is part of the guava library

**Comment by scottcsims** [comment]
Thank you, your response led me to the fix. Weld is trying to validate beans in the project. Weld is added with SeAuto. Guava is a transitive dependency of my project and the ServiceManager class is not in version 15 that I was using. I upgraded to the latest and it is fixed. 

```
    <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>18.0</version>
    </dependency>
```
