### ISSUE TITLE
Remote Webdriver Settings. 

### ISSUE THREAD

**Issue by scottcsims** [partnet/seauto#16]
Does SeAuto support setting an OS/platform for remote webdriver? I want to set it on the command line like this  -Dtest.config.browser=firefox -Dtest.config.platform=linux

**Comment by bbarke** [comment]
No, currently it does not support the platform. I think that could be a useful though

**Comment by scottcsims** [comment]
What is supported for remote webdriver? I think only firefox.

**Comment by bbarke** [comment]
For remote (running with `-Dtest.config.selenium.url`) Firefox, PhantomJs, and IE are supported. 

HTMLUnit doesn't make much sense to run remotely, and chrome still needs to be implemented. You can override the `getRemoteChromeWebDriver()` method inside of `config/selenium/ConfigurableDriverProvider` to get a remote Chrome instance working. Basically you'll need to create a DesiredCapabilities for Chrome, and feed that into the super.initRemoteWebDriver() method.

**Comment by fpedroza** [comment]
I'm confused. What would the intent behind this property be for? Why would
you care what OS a browser ran on?

**Comment by scottcsims** [comment]
I was thinking that all of the DesiredCapabilities were supported. In my case for some reason SeAuto is choosing our windows nodes on our grid. I was having issues with Firefox 38 and Selenium 45. Our linux nodes are configured with puppet so they are more updated and I was wanting to use them instead. I have seen Selenium have different bugs based on OS/browser combinations. We usually run on linux and chrome for the best combination of speed and stability. 
  Here is the reference to DesiredCapabilities. I wrote an internal library in ruby for our team to configure browser specific capabilities at one point.  It was quite challenging, so I am happy for what SeAuto can offer with Java and Spring. 
https://code.google.com/p/selenium/wiki/DesiredCapabilities

**Comment by bbarke** [comment]
I still think this is a reasonable case, for now we can add a `-Dtest.config.platform=linux`.
Overriding the default Desired Capabilities for each driver is easy enough as well by overriding one of the `config/selenium/ConfigurableDriverProvider` configurations.

**Comment by bbarke** [comment]
This is kindof related to #5
